---
- hosts: server1
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    #Apache Configuration
    - name: Installing necesary packages
      apt: name={{ item }} update_cache=yes state=latest
      loop:
        [
          "apache2",
          "mysql-server",
          "python3-pymysql",
          "php",
          "php-mysql",
          "libapache2-mod-php",
        ]

    #Curriculum configuration
    - name: Root document for website
      file:
        path: "/var/www/{{ website_http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: "0755"

    - name: Apache VirtualHost setup for website
      template:
        src: "files/apache.conf2.j2"
        dest: "/etc/apache2/sites-available/{{ website_http_conf }}"
      notify: Reload Apache

    - name: Enable website
      shell: /usr/sbin/a2ensite {{ website_http_conf }}
      notify: Reload Apache

    #Application configuration
    - name: Root document for application
      file:
        path: "/var/www/{{ app_http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: "0755"

    - name: Apache VirtualHost setup for application
      template:
        src: "files/apache.conf1.j2"
        dest: "/etc/apache2/sites-available/{{ app_http_conf }}"
      notify: Reload Apache

    - name: Enable application
      shell: /usr/sbin/a2ensite {{ app_http_conf }}
      notify: Reload Apache

    #Disable default apache site
    - name: Disable default apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    # MYSQL config
    - name: root user changing password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        host: localhost
        check_implicit_admin: yes
        login_password: "{{ mysql_old_root_password }}"
      become: yes

    - name: Creating database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Adding sql file
      copy:
        src: "{{ file_db }}"
        dest: "/tmp/{{ file_db }}"

    - name: Inserting database data
      mysql_db:
        name: "{{ db_name }}"
        state: import
        target: "/tmp/{{ file_db }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"

    # Copy source website code
    - name: Copying source website code
      copy:
        src: "{{ website_project_name }}"
        dest: "/var/www/{{ website_http_host }}"

    # Copy source app code
    - name: Copying source app code
      copy:
        src: "{{ app_project_name }}"
        dest: "/var/www/{{ app_http_host }}"

    - name: Deleting anonymous login
      mysql_user:
        name: ""
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Deleting test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    # Firewall configuration
    - name: "Allowing firewall HTTP port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
