---
mysql_root_password: " "
mysql_old_root_password: "new"
app_user: "elvira" # Usuario del servidor
website_http_host: "www.evargas.com" # Nombre del sitio del curriculum
website_http_conf: "www.evargas.com.conf" # Nombre del archivo de configuracion del sitio del curriculum
website_project_name: "curriculum"
app_http_host: "app.evargas.com" # Nombre del sitio de la aplicación
app_http_conf: "app.evargas.com.conf" # Nombre del archivo de configuracion del sitio la aplicación
app_project_name: "mysql"
http_port: "80" # Puerto en el que se habilitar
disable_default: yes # Sabe que sea
db_name: "mytest" # Nombre de la base de datos
file_db: "mytest.sql" # Nombre del archivo donde tienes el respaldo de la base de datos
name_new_user_db: "elvira" # Nombre de usuario con el que se conectara a la base de datos
pass_new_user_db: "elvira" # contraseña del nuevo usuario
